server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tpi-backend

  cloud:
    gateway:

      default-filters:
        - TokenRelay
        - AddResponseHeader=X-Gateway, Grupo114

      ####################################################
      # RUTAS CORRECTAS DEL TPI CON PREFIJO /api/**
      ####################################################
      routes:

        - id: ms-usuarios
          uri: http://ms-usuarios:8080
          predicates:
            - Path=/api/usuarios/**, /api/clientes/**, /api/transportistas/**
          filters:
            - TokenRelay

        - id: ms-tarifas
          uri: http://ms-tarifas:8080
          predicates:
            - Path=/api/tarifas/**
          filters:
            - TokenRelay

        - id: ms-camiones
          uri: http://ms-camiones:8080
          predicates:
            - Path=/api/camiones/**, /api/depositos/**
          filters:
            - TokenRelay

        - id: ms-solicitudes
          uri: http://ms-solicitudes:8080
          predicates:
            - Path=/api/solicitudes/**, /api/tramos/**, /api/rutas/**
          filters:
            - TokenRelay

      ####################################################
      # CORS COMPLETAMENTE CORRECTO PARA FRONTEND EN 5173
      ####################################################
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
              - "*"
              - "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
