server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/backend

  cloud:
    gateway:

      default-filters:
        - TokenRelay
        - AddResponseHeader=X-Gateway, Grupo114

      routes:

        # ===============================
        # MS-USUARIOS
        # ===============================
        - id: ms-usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/**, /clientes/**, /transportistas/**
          filters:
            - TokenRelay

        # ===============================
        # MS-TARIFAS
        # ===============================
        - id: ms-tarifas
          uri: http://localhost:8083
          predicates:
            - Path=/tarifas/**

        # ===============================
        # MS-CAMIONES
        # ===============================
        - id: ms-camiones
          uri: http://localhost:8084
          predicates:
            - Path=/camiones/**, /depositos/**

        # ===============================
        # MS-SOLICITUDES
        # ===============================
        - id: ms-solicitudes
          uri: http://localhost:8085
          predicates:
            - Path=/solicitudes/**, /tramos/**, /rutas/**
          filters:
            - TokenRelay

      # 🌐 CORS GLOBAL PARA VITE + GATEWAY
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
