server:
  port: 8080

spring:
  cloud:
    gateway:

      default-filters:
        - TokenRelay
        - AddResponseHeader=X-Gateway, Grupo114

      routes:

        - id: ms-usuarios
          uri: http://ms-usuarios:8080
          predicates:
            - Path=/usuarios/**
            - Path=/clientes/**
            - Path=/transportistas/**
          filters:
            - TokenRelay

        - id: ms-tarifas
          uri: http://ms-tarifas:8080
          predicates:
            - Path=/tarifas/**
          filters:
            - TokenRelay

        - id: ms-camiones
          uri: http://ms-camiones:8080
          predicates:
            - Path=/camiones/**
            - Path=/depositos/**
          filters:
            - TokenRelay

        - id: ms-solicitudes
          uri: http://ms-solicitudes:8080
          predicates:
            - Path=/solicitudes/**
            - Path=/tramos/**
            - Path=/rutas/**
          filters:
            - TokenRelay

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
